---
- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload Nginx

- name: Deploy Nginx site configuration from Jinja2 template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ project_name }}
    owner: root
    group: root
    mode: '0644'
  notify: Reload Nginx

- name: Enable the new site
  file:
    src: /etc/nginx/sites-available/{{ project_name }}
    dest: /etc/nginx/sites-enabled/{{ project_name }}
    state: link
  notify: Reload Nginx

- name: Test Nginx configuration
  command: nginx -t
  changed_when: false